### ISSUE TITLE
Broke on Android 11 Beta

### ISSUE THREAD

**Issue by ed-ponce** [apsun/uSticker#42] opened 2020-07-29 04:32 UTC
The stickers tab shows me a “something went wrong” disclaimer.

**Comment by apsun** [comment] 2020-07-29 15:42
I'm not going to subject myself to the pain of running an Android beta on my daily driver phone (unfortunately I only have one that's capable of running Android 11), so unfortunately I can't test this myself, but if you want to help you can grab a logcat dump of the moment you open the sticker tab in Gboard. That should help me determine where the issue is.

I don't think anything in Android 11 changed any features uSticker relies on, so currently I'm inclined to think this is a Gboard issue, but who knows. Also maybe try it out with other sticker packs and see if any of those work.

**Comment by ed-ponce** [comment] 2020-07-29 15:51
Thank you for answering! I reinstalled Gboard and it’s now partially working (doesn’t work with Camera pictures, but only with smaller files).

**Comment by apsun** [comment] 2020-09-09 04:53
Android 11 is now out and I have not been able to reproduce this on my Pixel 3. Closing.

**Closed as completed by apsun** 2020-09-09 04:53 UTC
