### ISSUE TITLE
Mais bytes por favor!!

### ISSUE THREAD

**Issue by nandoo025** [apsun/uSticker#28] opened 2020-03-24 19:44 UTC
Replace this line with any extra details that you may have.

--- 

App version: 1.5.3 (14) 
Gboard version: 9.1.8.300404574-release-armeabi-v7a (26910825) 
Android version: 5.1 (API22) 
Exception stacktrace: 
```
com.google.firebase.appindexing.zza: Indexable is 32649 bytes, which is larger than the maximum allowed size of 30000 bytes The invalid indexable url is: usticker://sticker
	at com.google.android.gms.common.api.internal.IStatusCallback$Stub.dispatchTransaction(com.google.android.gms:play-services-base@@17.1.0:20)
	at com.google.android.gms.internal.base.zaa.onTransact(com.google.android.gms:play-services-base@@17.1.0:3)
	at android.os.Binder.execTransact(Binder.java:451)
```

**Comment by apsun** [comment] 2020-03-26 07:22
Duplicate of #11.

**Closed as completed by apsun** 2020-03-26 07:22 UTC
