### ISSUE TITLE
uSticker gives this error after trying to import or change directory

### ISSUE THREAD

**Issue by MrRocketFX** [apsun/uSticker#46] opened 2020-12-24 01:41 UTC
uSticker version: 1.6.0 (16) 
Gboard version: 10.0.02.338070508-release-arm64-v8a (42277014) 
Android version: 10 (API29) 
Exception stacktrace: 
```
com.google.firebase.FirebaseApiNotAvailableException: API: AppIndexing.API is not available on this device. Connection failed with: ConnectionResult{statusCode=API_UNAVAILABLE, resolution=null, message=null}
	at com.google.firebase.FirebaseExceptionMapper.getException(Unknown Source:3)
	at com.google.android.gms.common.api.internal.zaf.zaa(com.google.android.gms:play-services-base@@17.1.0:1)
	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.zac(com.google.android.gms:play-services-base@@17.1.0:9)
	at com.google.android.gms.common.api.internal.GoogleApiManager$zaa.onConnectionFailed(com.google.android.gms:play-services-base@@17.1.0:33)
	at com.google.android.gms.common.api.internal.zabo.run(com.google.android.gms:play-services-base@@17.1.0:21)
	at android.os.Handler.handleCallback(Handler.java:883)
	at android.os.Handler.dispatchMessage(Handler.java:100)
	at com.google.android.gms.internal.base.zar.dispatchMessage(com.google.android.gms:play-services-base@@17.1.0:1)
	at android.os.Looper.loop(Looper.java:214)
	at android.os.HandlerThread.run(HandlerThread.java:67)
```

**Comment by apsun** [comment] 2020-12-24 02:02
Duplicate of #18.

**Closed as completed by apsun** 2020-12-24 02:02 UTC
